POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "media",
    "marcadores": [
        {"local": "Intelbras"},
        {"acao": "conversando"},
        {"nome": "matheus.santana"},
        {"conversa": "estranha"}
    ],
    "valores": [
        {"pessoas": 3},
        {"alienigenas": 8},
        {"vaca": 2}
    ]
}
